apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gjb3nttkx-python
  janus-idp.io/tekton: gjb3nttkx-python
  backstage.io/kubernetes-id: gjb3nttkx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gjb3nttkx-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
