apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gjb3nttkx-python 
  janus-idp.io/tekton: gjb3nttkx-python
  backstage.io/kubernetes-id: gjb3nttkx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gjb3nttkx-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml